### ISSUE TITLE
Encoding in Testklassen

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [fiverx/fiverx-api-java#12]
In den Groovy-Testklassen hat sich gezeigt, dass es Probleme mit dem Encoding-check gibt, wenn das default-Encoding mit dem Encoding in dem XML-File abgeglichen wird. Dies muss ggf. noch angepasst werden.

**Comment by frito** [comment]
Ich denke mal die hartcodieriten UTF-8 waren das Problem

**Comment by frito** [comment]
Jetzt laufen die Tests. Die Vermutung hatte sich bestätigt.
