### ISSUE TITLE
Unsauberer Umgang mit Encoding

### ISSUE THREAD

**Issue by frito** [fiverx/fiverx-api-java#5]
Unter Windows bzw. mit einem Standardencoding ungleich UTF-8 oder ISO-8859 gibt es unterschiedliche Fehler bei den JUnit Tests.

**Comment by frito** [comment]
Wenn man dem Compiler das Projektencoding <code>UTF-8</code> setzt, dann bleiben noch zwei Fehler übrig.

Dazu fügt man im im <code>build.gradle</code> z.B. folgende Zeile ein:
```
[compileJava, compileTestJava, compileGroovy, compileTestGroovy]*.options*.encoding = 'UTF-8'
```
Bei beiden anderen Tests schlägt lediglich der Assert fehl. Das eigentliche Ergebnis ist offensichtlich richtig, wenn man das zu Fuß überprüft.

**Comment by 5rx** [comment]
Läuft und OK. 1000 Dank!
Gruß Thomas
