### ISSUE TITLE
Support für PKCS12 Keystore

### ISSUE THREAD

**Issue by frito** [fiverx/fiverx-api-java#8]
Für die Verwendung von Keystores gibt es schon rudimentären Beispielcode, der in produktiven Code überführt werden muss.
Siehe: `de.fiverx.crypto.keystore.CreatePkcs12`und `de.fiverx.crypto.xml.StoreTest`.

**Comment by fiverx-gfi-bremen** [comment]
ich bastel heute mal den produktiven Code dafür. Ich hab mir den branch "introduce_pkcs12_capability" bereits gezogen. Ich geb den Snef dann später dazu, wenn ich fertig bin

**Comment by fiverx-gfi-bremen** [comment]
ich bastel heute mal den produktiven Code dafür. Ich hab mir den branch "introduce_pkcs12_capability" bereits gezogen. Ich geb den Snef dann später dazu, wenn ich fertig bin

**Comment by Captain-P-Goldfish** [comment]
vergessen zu schließen. Bereits vor Ewigkeiten beendet.
